/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem;

/**
 *
 * @author shaik
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnviewpres = new javax.swing.JButton();
        btngenstockrep = new javax.swing.JButton();
        btnmanageinv = new javax.swing.JButton();
        btnreg = new javax.swing.JButton();
        btnahp = new javax.swing.JButton();
        btnreghp = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        AdminDashboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        btnviewpres.setBackground(new java.awt.Color(255, 255, 51));
        btnviewpres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnviewpres.setText("View prescription and Dispense Medicine");
        btnviewpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewpresActionPerformed(evt);
            }
        });

        btngenstockrep.setBackground(new java.awt.Color(255, 255, 51));
        btngenstockrep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btngenstockrep.setText("Generate stock reports");
        btngenstockrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenstockrepActionPerformed(evt);
            }
        });

        btnmanageinv.setBackground(new java.awt.Color(255, 255, 51));
        btnmanageinv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmanageinv.setText("Manage inventory");
        btnmanageinv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageinvActionPerformed(evt);
            }
        });

        btnreg.setBackground(new java.awt.Color(255, 255, 51));
        btnreg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnreg.setText("Register staff/patient");
        btnreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregActionPerformed(evt);
            }
        });

        btnahp.setBackground(new java.awt.Color(255, 255, 51));
        btnahp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnahp.setText("Amend hospital policies");
        btnahp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnahpActionPerformed(evt);
            }
        });

        btnreghp.setBackground(new java.awt.Color(255, 255, 51));
        btnreghp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnreghp.setText("Register healthcare programs");
        btnreghp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreghpActionPerformed(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(255, 255, 51));
        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlogout.setText("logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        AdminDashboard.setText("Admin Dashboard");
        AdminDashboard.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                AdminDashboardAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnreg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnahp))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnreghp)
                                .addGap(67, 67, 67))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnmanageinv)
                                .addGap(125, 125, 125)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btngenstockrep)
                            .addComponent(btnlogout))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnviewpres)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(AdminDashboard)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(AdminDashboard)
                .addGap(34, 34, 34)
                .addComponent(btnviewpres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngenstockrep)
                    .addComponent(btnmanageinv))
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreg)
                    .addComponent(btnahp))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreghp)
                    .addComponent(btnlogout))
                .addContainerGap(540, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnviewpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewpresActionPerformed
    Viewprescription view = new Viewprescription();  // Create the new frame
    view.setVisible(true);                           // Show the new frame
    this.dispose();                                  // Close the current frame (optional)
    }//GEN-LAST:event_btnviewpresActionPerformed

    private void btnmanageinvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageinvActionPerformed
    InventoryManagement inventory = new InventoryManagement();  // Create the new frame
    inventory.setVisible(true);                           // Show the new frame
    this.dispose();                                      // Close the current frame (optional)
    }//GEN-LAST:event_btnmanageinvActionPerformed

    private void btnahpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnahpActionPerformed
    Amendhospitalpolicies amend = new Amendhospitalpolicies ();  // Create the new frame
    amend.setVisible(true);                           // Show the new frame
    this.dispose();                                      // Close the current frame (optional)
    }//GEN-LAST:event_btnahpActionPerformed

    private void btnregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregActionPerformed
    Registerstaffandpatients reg = new Registerstaffandpatients();  // Create the new frame
    reg.setVisible(true);                           // Show the new frame
    this.dispose();                                      // Close the current frame (optional)
    }//GEN-LAST:event_btnregActionPerformed

    private void btnreghpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreghpActionPerformed
    Registerhealthcareprograms reg = new Registerhealthcareprograms ();  // Create the new frame
    reg.setVisible(true);                           // Show the new frame
    this.dispose();  
    }//GEN-LAST:event_btnreghpActionPerformed

    private void btngenstockrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenstockrepActionPerformed
    GenerateStockReports generate = new GenerateStockReports();  // Create the new frame
    generate.setVisible(true);                           // Show the new frame
    this.dispose();                                      // Close the current frame (optional)
    }//GEN-LAST:event_btngenstockrepActionPerformed

    private void AdminDashboardAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_AdminDashboardAncestorAdded
        AdminDashboard.setText("Admin Dashboard");
        AdminDashboard.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 20));
    }//GEN-LAST:event_AdminDashboardAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDashboard;
    private javax.swing.JButton btnahp;
    private javax.swing.JButton btngenstockrep;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmanageinv;
    private javax.swing.JButton btnreg;
    private javax.swing.JButton btnreghp;
    private javax.swing.JButton btnviewpres;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
